apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secret
type: Opaque
stringData:
  WORDPRESS_DB_HOST: wordpress-db..ap-northeast-2.rds.amazonaws.com
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_USER: wpadmin
  WORDPRESS_DB_PASSWORD: wppassword123
